"use strict";

const secrets = {
  //   dbUrl: "mongodb://localhost:27017/webskeleton300",
  // dbUrl:"mongodb://localhost:27017/webskeleton3",
  //   dbName: "webskeleton300",
  threadCollection: "threads",
  userCollection: "users",
  sessionCollection: "appsessions",
  //   webUrl: "https://kaiindiaonline.com",
  //   webUrlVendor: "http://toyvala-admin.s3-website.ap-south-1.amazonaws.com",
  //   webUrlAdmin: "http://toyvala-admin.s3-website.ap-south-1.amazonaws.com",
  //   webUrlCustomer: "https://kaiindiaonline.com",
  // webUrl:"http://arjoi-vendor.s3-website.ap-south-1.amazonaws.com",
  // webUrlVendor:"http://arjoi-vendor.s3-website.ap-south-1.amazonaws.com",
  // webUrlAdmin:"http://arjoi-admin.s3-website.ap-south-1.amazonaws.com",
  // webUrlCustomer:"http://arjoi-main-website.s3-website.ap-south-1.amazonaws.com",
  roleCollection: "roles",
  categoryCollection: "categories",
  categoryBackupCollection: "categoriesBackup",
  productCollection: "products",
  product2Collection: "products2",
  businessCollection: "businesses",
  business2Collection: "businesses2",
  collectionCollection: "collection",
  productVariant: "variants",
  variantvalues: "variant_values",
  users2Collection: "users2",
  formCollection: "forms",
  tagCollection: "tags",
  notificationCollection: "notifications",
  voucher: "voucher",
  dbsubscribe: "subscribe",

  wallet: "wallet",
  redirectCollection: "redirect",
  elementCollection: "elements",
  chatCollection: "chats",
  orderCollection: "orders",
  messageCollection: "messages",
  transactionCollection: "transactions",
  communityCollection: "communities",
  postCollection: "posts",
  dealOfDay: "deals",

  commentCollection: "comments",
  bannerCollection: "banners",
  dbcms: "cms",

  shippingCollection: "shipping",
  cmsCollection: "cms",
  brandCollection: "brands",
  enquiryCollection: "enquiry",

  productOfTheMonth: "productOfTheMonth",
  availableVariantCollection: "availableVariantCollection",
  productCatalogue: "productCatalogue",
  pageCollection: "pages",
  typeCollection: "type",
  homeCategory: "homeCategory",
  orderStatusCollection: "orderstatus",
  sessionKey: [
    "ggggg",
    "aaaaa",
    "sssssss",
    "hhhhh",
    "ffff",
    "kkkkkk",
    "ttt",
    "aaaa",
  ],
  jwtKey: "supersecret",
  jwtDuration: 86400, //expires in 24 hours
  reqUrl: "http://localhost:1234",
  defaultSessionDuration: 24 * 60 * 60,
  sessionMode: "jwt",
  sessionType: "multi",
  superadminEmail: "surveyshimanshu@gmail.com",
  defaultRole: "vendor",
  alternateRole0: "user",
  defaultCurrency: "\u20B9",
  locationChangeDistance: 1, //km
  higherOrderRoles: ["superadmin", "admin", "vendor"],
  SMTPS_EMAIL: "online.sales@kai-group.co.in",
  SMTPS_PASSWORD: "online@123",
  SMTPS_URL: "smtp.gmail.com",
  // COMPANY_NAME:'Arjoi',
  COMPANY_NAME: "Kai India",
  TWILIO_ACCOUNT_SID: "AC36fff8d92a9cbbb21c6ac754b3ec1654",
  TWILIO_AUTH_TOKEN: "98bd18402cf57107b156b4ed2e16dd07",
  MSG91_AUTH_KEY: "350223AC9k2FWdU6035f947P1",
  MSG91_SENDER_ID: "TYVLSP",
  VALID_TWILIO_NUMBER: "+15614755502",
  FACEBOOK_CLIENT_ID: "1203798396690479",
  FACEBOOK_CLIENT_SECRET: "9d2f5ed2f2af49da908552ed0d046423",
  GOOGLE_CLIENT_ID:
    "555430730872-ra8pcq002612prf9i6t0713dclc07ogb.apps.googleusercontent.com",
  GOOGLE_CLIENT_SECRET: "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",
  AWS_USER_KEY: "AKIAREHYNAF2IKZ2C35L",
  AWS_USER_SECRET: "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",
  AWS_REGION: "ap-south-1",
  AWS_BUCKET_URL: "https://s3.ap-south-1.amazonaws.com",
  AWS_CLOUDFRONT_URL: "https://s3.ap-south-1.amazonaws.com",
  AWS_BUCKET_Assets: "kai-assets",
  AWS_BUCKET_Banner: "kai-assets",
  AWS_BUCKET_Documents: "kai-assets",
  AWS_BUCKET_Products: "kai-assets",
  AWS_BUCKET_Brand: "kai-assets",
  AWS_BUCKET_Profile: "kai-assets",
  AWS_BUCKET_Catgories: "kai-assets",
  AWS_BUCKET_Communities: "kai-assets",
  AWS_BUCKET_Tags: "kai-assets",

  AWS_BUCKET_Businesses: "kai-assets",
  AWS_BUCKET_Collection: "kai-assets",
  IMAGGA_API_KEY: "acc_2eba2eea5387579",
  IMAGGA_API_SECRET: "41ef31ec038b2db0f4d2d447cdd73076",

  CASHBACK_PERCENT: 100,
  WALLETCASH_USE_PERCENT: 100,

  // toyvala
  paytmMID: "Ganpat24704337507557",
  merchantKey: "e3GiTB6JnJ_6&Qeb",
  furl: "http://toyvala-main-website.s3-website.ap-south-1.amazonaws.com/cancelorder",
  surl: "http://toyvala-main-website.s3-website.ap-south-1.amazonaws.com/successorder",

  // arjoi
  // paytmMID:'ArjoiG65163877565166',
  // merchantKey:'Io9s6@d6Ixzl@jAo',
  // furl:'http://arjoi-main-website.s3-website.ap-south-1.amazonaws.com/cancelorder',
  // surl:'http://arjoi-main-website.s3-website.ap-south-1.amazonaws.com/successorder',
};
export default secrets;
/*
const secrets={
    dbUrl:"mongodb://localhost:27017/iluzexdb",
    dbCollection:"ilusers",
    sessionCollection:"appsessions",
    sessionKey:["ggggg","aaaaa","sssssss","hhhhh","ffff","kkkkkk","ttt","aaaa"],
    reqUrl:"http://localhost:1234",
    defaultSessionDuraion:2*60*60,
    SMTPS_EMAIL:"Senders Email",
    SMTPS_PASSWORD:"Password",
    SMTPS_URL:'smtp.gmail.com',
    COMPANY_NAME:'Tinkersale',
    TWILIO_ACCOUNT_SID:'twilio account sid',
    TWILIO_AUTH_TOKEN:'twilio account password',
    VALID_TWILIO_NUMBER:'twilio account number',
}
module.exports=secrets;
*/
